AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  personal-site-sam

  SAM Template for personal-site-backend
  
Globals:
  Function:
    Timeout: 3

Resources:
  VisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.visitorCountHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        VisitorCount:
          Type: Api
          Properties:
            Path: /visitor-count
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: Visitors

Outputs:
  VisitorCountApi:
    Description: "API Gateway endpoint URL for Prod stage for Visitor Count function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitor-count/"
